receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 100

exporters:
  otlphttp/traces:
    traces_endpoint: ${env:INGEST_TRACES_ENDPOINT}
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 30s

  otlphttp/logs:
    logs_endpoint: ${env:INGEST_LOGS_ENDPOINT}
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 30s

  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/traces, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs, debug]
